### ISSUE TITLE
Question about system requirements (disk space, RAM, etc)

### ISSUE THREAD

**Issue by unquietwiki** [blueprintue/blueprintue-self-hosted-edition#85]
Hey all. I'm interested in using this, but what system requirements are in place? Are the blueprint files stored directly into the database or the local filesystem? What kind of disk space usage should I expect? And is there any other processing, that would require memory or CPU above/beyond supporting the database? Thanks!

**Comment by rancoud** [comment]
Hi,

> Are the blueprint files stored directly into the database or the local filesystem?

Blueprints are stored on the local filesystem inside the `storage` folder.

> What kind of disk space usage should I expect?

About **website itself** if we don't take pictures of the user avatar, blueprint's thumbnail, and blueprints, it take less than **5 MO**.
About **blueprints** it can vary from less than **1 KO to 5 MO per blueprint**, because it's just a filetext.
About **database** it contains **8 tables using innoDB**.

> And is there any other processing, that would require memory or CPU above/beyond supporting the database? Thanks!

It only needs:
* a http server like Apache (https://httpd.apache.org/docs/2.4/en/platform/)
* PHP 7.4 (https://www.php.net/manual/en/install.php)
* a database like MariaDB (https://mariadb.com/kb/en/mariadb-hardware-requirements/)

You can run it on a raspberry pi 3.

**Comment by unquietwiki** [comment]
@rancoud Thank you for the quick response on this! This helps with my planning quite well.

**Comment by unquietwiki** [comment]
@rancoud Hey, wanted to follow-up on this. For the install I'm working with, I'm using a **t4g.medium** on AWS; the smaller versions kept disconnecting over the VPN solution I use with it.
